services:
  # Backend - Spring Boot
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: mysql
      DB_NAME: lilian_dev
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - lilian-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Frontend - Next.js
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://host.docker.internal:8080
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - lilian-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: lilian_dev
      MYSQL_USER: ${MYSQL_USER:-lilian}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Context/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lilian-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # phpMyAdmin (optional for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - lilian-network

networks:
  lilian-network:
    driver: bridge

volumes:
  mysql_data:
